"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SQS_DEV_SUBSCRIBE_ENDPOINT = exports.SQS_RECEIVE_WAIT_TIME_SECONDS = exports.AWS_USE_SQS_LOCAL = exports.AWS_DEFAULT_REGION = exports.KEYS_CHECK_PERIOD_IN_SECONDS = exports.AUTH0_API_IDENTIFIER = exports.LOGGER_DISABLE_CONSOLE_INTERCEPT = exports.DYNAMO_DB_URI = exports.ENVIRONMENT = exports.AWS_REGION = void 0;
const dotenv_1 = require("dotenv");
(0, dotenv_1.config)();
const { AWS_REGION = '', ENVIRONMENT = '', DYNAMO_DB_URI = '', AUTH0_API_IDENTIFIER = '', LOGGER_DISABLE_CONSOLE_INTERCEPT = false, KEYS_CHECK_PERIOD_IN_SECONDS = 120, AWS_DEFAULT_REGION = 'eu-west-1', AWS_USE_SQS_LOCAL = false, SQS_RECEIVE_WAIT_TIME_SECONDS = 20, SQS_DEV_SUBSCRIBE_ENDPOINT = 'http://localhost:5555', } = process.env;
exports.AWS_REGION = AWS_REGION;
exports.ENVIRONMENT = ENVIRONMENT;
exports.DYNAMO_DB_URI = DYNAMO_DB_URI;
exports.AUTH0_API_IDENTIFIER = AUTH0_API_IDENTIFIER;
exports.LOGGER_DISABLE_CONSOLE_INTERCEPT = LOGGER_DISABLE_CONSOLE_INTERCEPT;
exports.KEYS_CHECK_PERIOD_IN_SECONDS = KEYS_CHECK_PERIOD_IN_SECONDS;
exports.AWS_DEFAULT_REGION = AWS_DEFAULT_REGION;
exports.AWS_USE_SQS_LOCAL = AWS_USE_SQS_LOCAL;
exports.SQS_RECEIVE_WAIT_TIME_SECONDS = SQS_RECEIVE_WAIT_TIME_SECONDS;
exports.SQS_DEV_SUBSCRIBE_ENDPOINT = SQS_DEV_SUBSCRIBE_ENDPOINT;
//# sourceMappingURL=consts.js.map