import { config } from 'dotenv'

config()


const {
    AWS_REGION = '',
    ENVIRONMENT = '',
    DYNAMO_DB_URI = '',
    AUTH0_API_IDENTIFIER = '',
    LOGGER_DISABLE_CONSOLE_INTERCEPT = false,
    KEYS_CHECK_PERIOD_IN_SECONDS = 120,
    AWS_DEFAULT_REGION = 'eu-west-1',
    AWS_USE_SQS_LOCAL = false,
    SQS_RECEIVE_WAIT_TIME_SECONDS = 20,
    SQS_DEV_SUBSCRIBE_ENDPOINT = 'http://localhost:5555',
} = process.env

export {
    AWS_REGION,
    ENVIRONMENT,
    DYNAMO_DB_URI,
    LOGGER_DISABLE_CONSOLE_INTERCEPT,
    AUTH0_API_IDENTIFIER,
    KEYS_CHECK_PERIOD_IN_SECONDS,
    AWS_DEFAULT_REGION,
    AWS_USE_SQS_LOCAL,
    SQS_RECEIVE_WAIT_TIME_SECONDS,
    SQS_DEV_SUBSCRIBE_ENDPOINT,
}