name: Deploy Serverless Application

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows this workflow to push back to the repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all tags and branches

    - name: Use Node.js 18.x
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install

    - name: Configure git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Bump version and push tag
      run: |
        npm version patch -m "chore(release): bump version to %s [skip ci]"
        git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      id: deploy
      run: |
        echo "Deploying..."
        DEPLOY_OUTPUT=$(npx serverless deploy)
        echo "$DEPLOY_OUTPUT"
        echo "::set-output name=deploy_output::$DEPLOY_OUTPUT"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # New step to parse and display the deployment output
    - name: Display Deployment Output and Endpoints
      run: |
        echo "Deployment Successful"
        echo "Deployment Output:"
        echo "${{ steps.deploy.outputs.deploy_output }}"
        echo "Extracted Endpoints:"
        echo "${{ steps.deploy.outputs.deploy_output }}" | grep -Eo 'https?://[a-zA-Z0-9./?=_-]*' || echo "No endpoints extracted. Check the deployment output for details."
